"use client"

import { Card, CardContent } from "@/components/ui/card"
import { Lightbulb } from "lucide-react"
import { motion } from "framer-motion"

interface TimelineRecommendationsProps {
  recommendations: string[]
  isDarkMode: boolean
}

export default function TimelineRecommendations({ recommendations, isDarkMode }: TimelineRecommendationsProps) {
  if (!recommendations || recommendations.length === 0) return null

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
      <Card
        className={`border rounded-3xl ${isDarkMode ? "border-[#334155] bg-[#1e1e24]" : "border-[#e2e8f0] bg-white"}`}
      >
        <CardContent className="p-6">
          <div className="flex items-center gap-3 mb-4">
            <div
              className={`flex items-center justify-center h-8 w-8 rounded-full ${
                isDarkMode ? "bg-[#6366f1]/10" : "bg-[#3b82f6]/10"
              }`}
            >
              <Lightbulb className={`h-4 w-4 ${isDarkMode ? "text-[#a5b4fc]" : "text-[#3b82f6]"}`} />
            </div>
            <h3 className="font-medium text-[#1e293b] dark:text-white">AI-Generated Recommendations</h3>
          </div>

          <ul className="space-y-3">
            {recommendations.map((recommendation, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.1 }}
                className="flex items-start gap-2"
              >
                <div
                  className={`mt-1 h-4 w-4 rounded-full flex items-center justify-center ${
                    isDarkMode ? "bg-[#6366f1]" : "bg-[#3b82f6]"
                  }`}
                >
                  <div className="h-1.5 w-1.5 bg-white rounded-full" />
                </div>
                <p className="text-sm text-[#334155] dark:text-[#e2e8f0]">{recommendation}</p>
              </motion.li>
            ))}
          </ul>

          <div className="mt-4 pt-3 border-t border-[#e2e8f0] dark:border-[#334155]">
            <p className="text-xs text-[#64748b] dark:text-[#94a3b8] italic">
              These recommendations are generated by AI based on your incident details and{" "}
              <span className="font-medium">compliance requirements</span>.
            </p>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
